version: '3'
services:
  app:
    build: .
    container_name: insta-filtring-cmnts
    ports:
      - "3500:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
